### ISSUE TITLE
The client stucks when I try to connect to the server

### ISSUE THREAD

**Issue by andrezoo** [AlexTunder/ossa#13]
I wrote a server for this chat, tried to connect to it, and got a problem. It just stopped accepting any inputs :( 
![Снимок](https://user-images.githubusercontent.com/44097385/109254332-039d7400-781c-11eb-858c-0fcd04511ef2.PNG)

**Comment by andrezoo** [comment]
Server's code: https://gist.github.com/andrezoo/a01d3ad381396743a554572aa3d7b531

**Comment by AlexTunder** [comment]
Why are you use "000f0010" (auth code) as answer for every request? You should use one of 4 connection code from `network/OPTC API codes.txt`: `000faa1c - open (hardware)`, `000faf1c - open (MAC)`, `000f0010 - username and pwd` or `000f0a10 - pwd only`
you should make handlers for every type of requests

**Comment by andrezoo** [comment]
Oh, sorry, I see. Thank you for your help. I am blind
